### ISSUE TITLE
"cinnamon.dewarim.com/*" links in ReadMe are down

### ISSUE THREAD

**Issue by rupinderjeet** [dewarim/data-tools-for-reddit#10]
I guess because your server is down due to this comment:

> Note: My torrent server is currently offline, as I have to re-evaluate copyright and upcoming changes in EU data protection laws

Since the last ReadMe update was 4 years ago, is there an update? Or is the submissions torrent available on academictorrents?

**Comment by dewarim** [comment]
The submissions can be found at https://files.pushshift.io/reddit/submissions/ 

I will no longer host comments / submissions myself, else I would have to check them for problematic / copyrighted content to prevent cease and desist letters (which tend to come with hefty lawyer's fees in my country).
